package cn.lzh.utils.io;

import android.content.Context;
import androidx.annotation.NonNull;

import java.util.List;

import static cn.lzh.utils.io.StreamUtil.getStrings;
import static cn.lzh.utils.io.StreamUtil.readString;

/**
 * Created by lzh on 2018/12/26.<br/>
 * @see #getFileFromRaw(Context, int)
 * @see #getFileToListFromRaw(Context, int)
 */
public final class RawUtil {

    private RawUtil() {
        throw new UnsupportedOperationException("Cannot be instantiated");
    }
    /**
     * get content from a raw resource. This can only be used with resources whose value is the name of an asset files
     * -- that is, it can be used to open drawable, sound, and raw resources; it will fail on string and color
     * resources.
     *
     * @param context Context
     * @param resId   The resource identifier to open, as generated by the appt tool.
     * @return
     */
    @NonNull
    public static String getFileFromRaw(@NonNull Context context, int resId) {
        return readString(context.getResources().openRawResource(resId));
    }

    /**
     * same to {@link #getFileFromRaw(Context, int)}, but return type is List<String>
     *
     * @param context Context
     * @param resId   资源id
     */
    @NonNull
    public static List<String> getFileToListFromRaw(@NonNull Context context, int resId) {
        return getStrings(context.getResources().openRawResource(resId));
    }

}
