package cn.lzh.utils.io;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import java.io.IOException;
import java.io.InputStream;
import java.util.List;

import static cn.lzh.utils.io.StreamUtil.getStrings;
import static cn.lzh.utils.io.StreamUtil.readString;

/**
 * ResourceUtil
 *
 * @author open source
 * @see #getResourceId(Context, String)
 * @see #geFileFromAssets(Context, String)
 * @see #getFileToListFromAssets(Context, String)
 * @see #getFileFromRaw(Context, int)
 * @see #getFileToListFromRaw(Context, int)
 */
public class ResourceUtil {

    private ResourceUtil() {
        throw new UnsupportedOperationException("Cannot be instantiated");
    }

    /**
     * 根据资源id的名称获取资源的id
     *
     * @param context        Context
     * @param resourceIdName 资源名称
     */
    public static int getResourceId(Context context, String resourceIdName) {
        return context.getResources().getIdentifier(resourceIdName, null, null);
    }

    public static String geFileFromAssets(@NonNull Context ctx, @NonNull String name) throws IOException {
        return readString(ctx.getAssets().open(name));
    }

    /**
     * same to {@link #geFileFromAssets(Context, String)}, but return type is List<String>
     *
     * @param context  Context
     * @param fileName 文件名
     */
    @Nullable
    public static List<String> getFileToListFromAssets(@NonNull Context context, String fileName) {
        try {
            return getStrings(context.getResources().getAssets().open(fileName));
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    public static Bitmap getImageFromAssetsFile(Context ct, String fileName) {
        InputStream is = null;
        try {
            is = ct.getAssets().open(fileName);
            return BitmapFactory.decodeStream(is);
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                if (is != null) is.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        return null;
    }
    /**
     * get content from a raw resource. This can only be used with resources whose value is the name of an asset files
     * -- that is, it can be used to open drawable, sound, and raw resources; it will fail on string and color
     * resources.
     *
     * @param context Context
     * @param resId   The resource identifier to open, as generated by the appt tool.
     * @return
     */
    @NonNull
    public static String getFileFromRaw(@NonNull Context context, int resId) {
        return readString(context.getResources().openRawResource(resId));
    }

    /**
     * same to {@link #getFileFromRaw(Context, int)}, but return type is List<String>
     *
     * @param context Context
     * @param resId   资源id
     */
    @NonNull
    public static List<String> getFileToListFromRaw(@NonNull Context context, int resId) {
        return getStrings(context.getResources().openRawResource(resId));
    }
}
